config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :polls, only: [:index] do
    resources :candidates, only: [:index]
  end
  resources :votes, only: [:create, :new, :show]
  devise_for :users
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :user
  belongs_to :poll

  has_many :votes

  validates :user, uniqueness: { scope: :poll }

  def score
    votes.count
  end
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :candidates
  has_many :rules

  validates :name, uniqueness: true
end

app/models/rule.rb
class Rule < ApplicationRecord
  enum key: { candidate_voter_limit: 'candidate_voter_limit',
              self_vote: 'self_vote' }, _prefix: true

  belongs_to :poll

  validates :key, uniqueness: { scope: :poll }

  def check(vote)
    send("check_#{key}", vote)
  end

  def check_self_vote(vote)
    # Values: '0' => disabled, '1' => enabled
    enabled = ActiveModel::Type::Boolean.new.cast(value)
    valid = enabled || vote.candidate.user != vote.voter
    vote.errors.add :candidate, "can't be yourself" unless valid
  end

  def check_candidate_voter_limit(vote)
    # Example value: '1,P1D' => limit: 1, period: 1 day
    # Ref: https://en.wikipedia.org/wiki/ISO_8601#Durations
    limit, period = value.split(',')
    limit = limit.to_i
    from = ActiveSupport::Duration.parse(period).ago
    votes = Vote.where(candidate: vote.candidate, voter: vote.voter)
    count = votes.where('created_at > ?', from).count
    vote.errors.add :candidate, 'reached your limit' if count >= limit
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def to_s
    email
  end

  def vote(candidate)
    Vote.create(candidate: candidate, voter: self)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :candidate
  belongs_to :voter, class_name: 'User'

  validate :check_rules, on: :create

  def check_rules
    candidate.poll.rules.each { |rule| rule.check(self) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    if params[:poll_id]
      poll = Poll.find(params[:poll_id])
      @candidates = poll.candidates
    else
      @candidates = Candidate.where(poll: nil)
    end
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @polls = Poll.all
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show]
  before_action :authenticate_user!, only: [:create]

  def new
    @vote = Vote.new
  end

  def create
    candidate = Candidate.find(vote_params[:candidate_id])
    @vote = current_user.vote(candidate)

    respond_to do |format|
      if @vote.persisted?
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_vote
    @vote = Vote.find(params[:id])
  end

  def vote_params
    params.require(:vote).permit(:candidate_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
  def link_to_vote(candidate_id)
    link_to 'Vote', votes_path(vote: { candidate_id: candidate_id }), method: :post
  end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidates</h1>

<table>
  <thead>
    <tr>
      <th>Candidate</th>
      <th>Score</th>
      <% if current_user %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.user.email %></td>
        <td><%= candidate.score %></td>
        <% if current_user %>
          <td><%= link_to_vote(candidate.id) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Katan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <hr/>
    <%= link_to 'Home', root_path %>
    <%= link_to 'Polls', polls_path %>
  </body>
</html>

app/views/polls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Polls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.name %></td>
        <td><%= link_to 'Candidates', poll_candidates_path(poll) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/votes/_form.html.erb
<%= form_with(model: vote, local: true) do |form| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
        <% vote.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :candidate_id %>
    <%= form.text_field :candidate_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form', vote: @vote %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Candidate:</strong>
  <%= @vote.candidate %>
</p>

<p>
  <strong>Voter:</strong>
  <%= @vote.voter %>
</p>

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome</h1>

<p>
  <% if current_user %>
    <span><%= current_user %></span>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to 'Login', new_user_session_path %>
  <% end %>
</p>